const status = {
	"EMPTY": 0,
	"WAITING_FOR_NAME": 1,
	"WAITING_FOR_ACCEPT": 2,
	"WAITING_FOR_MOBILE": 3,
	"WAITING_FOR_PASSWORD": 4,
	"WAITING_FOR_ADDRESS": 5,
	"WAITING_FOR_HEADTEACHER": 6,
	"WAITING_FOR_DORM": 7,
	"CHECKING": 8,
	"WAITING_FOR_ACCEPT": 9,
	"INITING": 0,
	"EDITING": 1
}

export default status
